language: python
sudo: false
python: 2.7
env:
    - TOX_ENV=flake8
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py27-djangomaster
matrix:
    allow_failures:
        - env: TOX_ENV=py27-django19
        - env: TOX_ENV=py27-django110
        - env: TOX_ENV=py27-djangomaster
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
