[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-invite"
description = "A Django application for inviting users to a site."
readme = "README.md"
version = "6.0.0"
keywords=["django", "invite", "invitation"]
requires-python = ">=3.12"
license = { text = "LICENSE" }
authors = [
  {name = "University of North Texas Libraries", email = "mark.phillips@unt.edu"}
]
classifiers = [
    "Natural Language :: English",
    "Environment :: Web Environment",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application :: User Management",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: System Administrators",
    "Intended Audience :: End Users/Desktop",
    "Framework :: Django :: 6.1",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "Django @ git+https://github.com/django/django.git@stable/6.1.x", 
    "pytz~=2022.3",
]

[project.urls]
Homepage = "https://github.com/unt-libraries/django-invite"
Repository = "https://github.com/unt-libraries/django-invite.git"

[project.optional-dependencies]
test = [
    "pytest~=8.4.0",
    "pytest-django~=4.5.2",
    "ruff~=0.15.9",
    "tox==4.28.1",
]

[tool.ruff]
line-length = 99
target-version = "py312"
extend-exclude = ['migrations']

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "F", "W"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings.test"
addopts = ["--nomigrations", "--create-db"]

[tool.tox]
legacy_tox_ini = """
    [tox]
    envlist =
        py{312,313,314}
        ruff

    [pytest]
    DJANGO_SETTINGS_MODULE = tests.settings.test

    [testenv]
    extras =
        test
    commands = 
        pytest -s
    allowlist_externals = pytest

    [testenv:ruff]
    basepython = python3.14
    deps =
        ruff
    commands =
        ruff check   
"""