# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-26 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_abstract_invitation_auto_now_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='activation_code',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='unique id, generated on email submission', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='date_invited',
            field=models.DateField(auto_now_add=True, help_text='the day on which the superuser invited the potential member'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(help_text="the potential member's email address", max_length=41),
        ),
        migrations.AlterField(
            model_name='passwordresetinvitation',
            name='activation_code',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='unique id, generated on email submission', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetinvitation',
            name='date_invited',
            field=models.DateField(auto_now_add=True, help_text='the day on which the superuser invited the potential member'),
        ),
        migrations.AlterField(
            model_name='passwordresetinvitation',
            name='email',
            field=models.EmailField(help_text="the potential member's email address", max_length=41),
        ),
    ]
