# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0004_auto_20191126_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetinvitation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
